import React,{useEffect,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {MapView} from './MapView';
import * as C from './core';
import './style.css';
const base=import.meta.env.BASE_URL;
type Local={quest:C.Quest;session?:C.Session;history:C.Session[]};
const load=(key:string):Local=>{try{const x=JSON.parse(localStorage.getItem(key)||'null');if(x?.quest&&Array.isArray(x.quest.boundary)&&Array.isArray(x.quest.points)&&Array.isArray(x.history)){if(x.session?.status==='active'){x.session.status='paused';C.breakTrack(x.session);}return x;}}catch{}return {quest:C.demoQuest(),history:[]};};
const label:Record<C.Status,string>={active:'探索进行中',paused:'探索已暂停',completed:'探索完成',failed:'体力耗尽',ended:'提前结束'};
function App(){
 const [data,setData]=useState<Local>(()=>load('tq:TrailQuest-web:local')),[tab,setTab]=useState<'explore'|'history'|'help'>('explore'),[mode,setMode]=useState<'boundary'|C.Kind>('boundary');
 const [fix,setFix]=useState<C.Fix>(),[gps,setGps]=useState('等待定位'),[focus,setFocus]=useState<C.Coord>(),[focusVersion,setFocusVersion]=useState(0),[notice,setNotice]=useState(''),[sync,setSync]=useState('本机已保存'),[demoMoving,setDemoMoving]=useState(false),[radius,setRadius]=useState(35),[selected,setSelected]=useState<C.Session>(),[wakeEnabled,setWakeEnabled]=useState(false);
 const [draftBoundary,setDraftBoundary]=useState<C.Coord[]|null>(null);
 const dataRef=useRef(data),pendingFocus=useRef(false),watch=useRef<number|undefined>(undefined),demoTimer=useRef<ReturnType<typeof setInterval>|undefined>(undefined),wake=useRef<{release:()=>Promise<void>}|null>(null);dataRef.current=data;
 const secure=window.isSecureContext,session=data.session;
 function toast(text:string){setNotice(text);}
 function stopWatch(){if(watch.current!==undefined){navigator.geolocation.clearWatch(watch.current);watch.current=undefined;}}
 function stopDemo(){if(demoTimer.current)clearInterval(demoTimer.current);demoTimer.current=undefined;setDemoMoving(false);}
 function changeSession(action:(s:C.Session)=>void){setData(old=>{if(!old.session)return old;const s=structuredClone(old.session);action(s);return {...old,session:s};});}
 function receive(f:C.Fix){if(pendingFocus.current&&C.usable(f)){pendingFocus.current=false;setFocus(f.position);setFocusVersion(v=>v+1);}setFix(f);setGps(C.usable(f)?`定位精度 ±${Math.round(f.accuracy)}m`:'定位信号较弱，暂停判定');changeSession(s=>{const n=s.events.length;C.ingest(s,f);if(s.events.length>n)setNotice(s.events.at(-1)!.text);});}
 function locate(){if(!secure){toast('真实定位需要 HTTPS。当前可先体验演示探索。');return;}if(!navigator.geolocation){toast('此浏览器不支持定位');return;}setGps('正在获取位置…');stopWatch();watch.current=navigator.geolocation.watchPosition(p=>{const f={position:{lat:p.coords.latitude,lng:p.coords.longitude},accuracy:p.coords.accuracy,timestamp:p.timestamp};receive(f);},e=>{setGps(e.code===1?'定位未授权':'暂时无法定位');toast(e.code===1?'请在浏览器设置中允许此网站访问位置。':'定位暂时不可用，请到开阔处重试。');changeSession(C.breakTrack);},{enableHighAccuracy:true,maximumAge:0,timeout:15000});}
 useEffect(()=>()=>{stopWatch();if(demoTimer.current)clearInterval(demoTimer.current);},[]);
 useEffect(()=>{try{localStorage.setItem('tq:TrailQuest-web:local',JSON.stringify(data));setSync('已保存在此浏览器');}catch{setSync('本机空间不足，请导出记录');}},[data]);
 useEffect(()=>{const hide=()=>{if(document.hidden){stopDemo();changeSession(C.pause);wake.current?.release();setWakeEnabled(false);}};document.addEventListener('visibilitychange',hide);return()=>document.removeEventListener('visibilitychange',hide);},[]);
 useEffect(()=>{if(session&&C.finished(session)){stopDemo();stopWatch();wake.current?.release();setWakeEnabled(false);}},[session?.status]);
 useEffect(()=>{if(!notice)return;const t=setTimeout(()=>setNotice(''),6500);return()=>clearTimeout(t);},[notice]);
 function tap(p:C.Coord){if(session){if(session.demo&&session.status==='active')moveDemo(p);return;}if(mode==='boundary'){
  if(draftBoundary===null&&data.quest.boundary.length>=3){toast('当前区域已完成，请先点击“重新圈定区域”');return;}
  const current=draftBoundary??data.quest.boundary;if(current.length>=50){toast('最多 50 个边界顶点');return;}
  if(current.length&&C.distance(current.at(-1)!,p)<5){toast('相邻顶点请间隔至少 5 米');return;}
  const next=[...current,p];if(next.length>=3){const error=C.boundaryError(next);if(error==='边界不能交叉或重叠'){toast(error);return;}}
  setDraftBoundary(next);return;
 }setData(old=>{const q=structuredClone(old.quest);const e=C.boundaryError(q.boundary);if(e){toast(e);return old;}if(!C.contains(p,q.boundary)){toast('请把点位放在探索区域内');return old;}q.points.push({id:C.id(),name:C.kinds[mode].name+' '+(q.points.filter(x=>x.kind===mode).length+1),kind:mode,position:p,radius});return {...old,quest:q};});}
 function finishBoundary(){if(draftBoundary===null)return;const error=C.boundaryError(draftBoundary);if(error){toast(error);return;}setData(old=>({...old,quest:{...old.quest,boundary:draftBoundary,points:[]}}));setDraftBoundary(null);setMode('treasure');toast('区域已完成，请在地图上布置点位');}
 function begin(demo=false){if(draftBoundary!==null){toast('请先完成或取消圈区');return;}const error=C.questError(data.quest);if(error){toast(error);return;}if(!demo&&(!fix||!C.usable(fix)||!C.contains(fix.position,data.quest.boundary))){toast('请先定位并走进区域，等待精度达到 30 米以内。');locate();return;}stopWatch();const s=C.start(data.quest,demo);if(demo){const b=data.quest.boundary;const p={lat:b.reduce((v,p)=>v+p.lat,0)/b.length,lng:b.reduce((v,p)=>v+p.lng,0)/b.length};setFix({position:p,accuracy:3,timestamp:Date.now()});setGps('演示位置 · 非真实 GPS');}setData({...data,session:s});if(!demo)locate();toast(demo?'演示开始：点击地图移动，或走向下一点。':'探索开始，走近点位并停留片刻。');}
 function moveDemo(target:C.Coord){if(!dataRef.current.session?.demo||dataRef.current.session.status!=='active')return;stopDemo();stopWatch();setDemoMoving(true);const from=dataRef.current.session.lastFix?.position||fix?.position||target;const steps=Math.max(1,Math.ceil(C.distance(from,target)/10));let n=0;demoTimer.current=setInterval(()=>{n++;const t=Math.min(1,n/steps);receive({position:{lat:from.lat+(target.lat-from.lat)*t,lng:from.lng+(target.lng-from.lng)*t},accuracy:3,timestamp:Date.now()});setGps('演示位置 · 非真实 GPS');if(n>=steps+8)stopDemo();},500);}
 function nextDemo(){const s=dataRef.current.session;if(!s)return;const next=s.quest.points.find(p=>!s.found.includes(p.id));if(next)moveDemo(next.position);}
 async function wakeScreen(){try{if(!('wakeLock'in navigator)){toast('此浏览器不支持保持亮屏');return;}wake.current=await (navigator as any).wakeLock.request('screen');setWakeEnabled(true);(wake.current as any).addEventListener('release',()=>setWakeEnabled(false));}catch{toast('无法保持亮屏，请检查系统电量设置');}}
 function archive(){stopWatch();stopDemo();setData(old=>old.session?{...old,history:[old.session,...old.history.filter(s=>s.id!==old.session!.id)],session:undefined}:old);}
 function exportSession(s:C.Session){const blob=new Blob([JSON.stringify(s,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='trailquest-'+s.id+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 const viewing=tab==='history'?selected:session,q=viewing?.quest||data.quest,visiblePoints=viewing?q.points.filter(p=>viewing.demo||viewing.found.includes(p.id)):q.points,editingBoundary=tab==='explore'&&!session&&draftBoundary!==null;
 return <div className="app"><header className="topbar"><a className="brand" href={base} aria-label="野趣探索首页"><img src={base+"icon.svg"}/><span>野趣探索<small>TRAILQUEST</small></span></a><nav aria-label="主导航">{(['explore','history','help']as const).map((t,i)=><button key={t} className={tab===t?'selected':''} onClick={()=>setTab(t)}>{['探索地图','我的足迹','玩法说明'][i]}</button>)}</nav><div className="account">本机存档<span>无需登录</span></div></header>
 <main className="workspace"><aside className="panel">{tab==='explore'?<><div className="eyebrow">STEP OUT. FIND SOMETHING.</div><h1>{session?'每一步，都有发现。':'把平凡的街角，\n变成一场探险。'}</h1><p className="intro">{session?'沿着真实的路，寻找藏在地图里的惊喜。':'圈一块喜欢的地方，放下宝藏，然后出发。'}</p>{!session?<><div className="section-top"><h2>创建你的探索</h2><span className="badge">自由布点</span></div><label className="field">探索名称<input value={data.quest.name} maxLength={60} onChange={e=>setData({...data,quest:{...data.quest,name:e.target.value}})}/></label><div className="mode-tabs"><button className={mode==='boundary'?'on':''} onClick={()=>setMode('boundary')}>01 圈定区域</button><button className={mode!=='boundary'?'on':''} onClick={()=>{if(draftBoundary!==null){toast('请先完成或取消圈区');return;}setMode('treasure');}}>02 布置点位</button></div>{mode==='boundary'?<div className="hintbox">{draftBoundary!==null?<><strong>依次点击地图添加顶点</strong><p>边线保持开放；至少 3 个点后点击“完成圈区”才会闭合。拖动地图可平移，地图拖动不会添加顶点。{data.quest.points.length>0?'完成新区域后会清除旧点位。':''}</p><div className="inline"><span>{draftBoundary.length} 个顶点</span><button className="textbutton" disabled={!draftBoundary.length} onClick={()=>setDraftBoundary(draftBoundary.slice(0,-1))}>撤销上一点</button></div><div className="action-row"><button className="secondary" disabled={draftBoundary.length<3} onClick={finishBoundary}>完成圈区</button><button className="textbutton" onClick={()=>setDraftBoundary(null)}>取消重画</button></div></>:<><strong>当前区域已完成</strong><p>{data.quest.boundary.length} 个顶点。需要修改时重新圈定；边线会在完成后闭合。</p><button className="secondary" onClick={()=>setDraftBoundary([])}>重新圈定区域</button></>}</div>:<><div className="kind-grid">{(Object.keys(C.kinds)as C.Kind[]).map(k=><button key={k} className={mode===k?'on':''} onClick={()=>setMode(k)}><b style={{color:C.kinds[k].color}}>{C.kinds[k].icon}</b>{C.kinds[k].name}<small>{C.kinds[k].effect}</small></button>)}</div><label className="range">触发范围 <b>{radius} 米</b><input type="range" min="15" max="80" step="5" value={radius} onChange={e=>setRadius(+e.target.value)}/></label></>}
 <div className="section-top"><h3>探索点位</h3><span>{q.points.length} 个</span></div><div className="point-list">{q.points.length===0?<p className="empty-small">你的第一份宝藏，等你放下。</p>:q.points.map(p=><div key={p.id} className="point-row"><span className={'point-icon '+p.kind}>{C.kinds[p.kind].icon}</span><div><input aria-label={'点位名称 '+p.name} value={p.name} maxLength={60} onChange={e=>setData({...data,quest:{...q,points:q.points.map(x=>x.id===p.id?{...x,name:e.target.value}:x)}})}/><small>{C.kinds[p.kind].name} · {p.radius} 米</small></div><button aria-label={'删除 '+p.name} className="iconbutton" onClick={()=>setData({...data,quest:{...q,points:q.points.filter(x=>x.id!==p.id)}})}>×</button></div>)}</div>
 {secure&&<button className="primary" onClick={()=>begin(false)}>开始真实探索 <span>↗</span></button>}<button className="secondary" onClick={()=>begin(true)}>先试试演示探索</button><div className="inline bottom-tools"><button className="textbutton" onClick={()=>{if(confirm('清空当前草稿并重新圈区？')){setData({...data,quest:C.blank()});setDraftBoundary([]);setMode('boundary');}}}>新建空白关卡</button><button className="textbutton" onClick={()=>{if(confirm('用示例关卡替换当前草稿？')){const quest=C.demoQuest(fix?.position);setData({...data,quest});setDraftBoundary(null);setMode('boundary');setFocus(quest.boundary[0]);setFocusVersion(v=>v+1);}}}>加载示例</button></div></>:<><div className="section-top"><h2>{session.quest.name}</h2><span className="badge">{session.demo?'演示':'实地'}</span></div><div className="session-status">● {label[session.status]}</div><div className="stats"><div><b>{session.score}</b><span>探索积分</span></div><div><b>{session.health}<small>/100</small></b><span>剩余体力</span></div><div><b>{Math.round(session.distance)}<small>m</small></b><span>已走距离</span></div><div><b>{session.found.length}<small>/{session.quest.points.length}</small></b><span>发现点位</span></div></div>{C.finished(session)?<><div className="celebration">{session.status==='completed'?'✦ 满载而归':'探索告一段落'}<p>路线和事件已经记下，下一次再见。</p></div><button className="primary" onClick={archive}>保存到历史并返回 ↗</button></>:<><div className="hintbox"><strong>{session.demo?'演示探索 · 点击地图移动':'未发现的点位已隐藏'}</strong><p>{session.demo?'也可以点击下方按钮，自动前往下一个点位。演示记录会单独标记。':'靠近点位后停留几秒。切后台或锁屏会自动暂停。'}</p></div>{session.demo&&<button className="primary" disabled={demoMoving||session.status!=='active'} onClick={nextDemo}>{demoMoving?'正在前往并确认位置…':'走向下一点 →'}</button>}<div className="action-row"><button className="secondary" onClick={()=>{stopDemo();if(session.status==='active'){changeSession(C.pause);stopWatch();}else if(session.demo){changeSession(C.resume);}else if(fix&&C.usable(fix)&&C.contains(fix.position,session.quest.boundary)){changeSession(C.resume);locate();}else{toast('请重新定位并回到区域再继续');locate();}}}>{session.status==='active'?'暂停探索':'继续探索'}</button><button className="secondary danger" onClick={()=>{if(confirm('结束本次探索并保留足迹？')){stopDemo();changeSession(C.end);stopWatch();}}}>结束探索</button></div>{!session.demo&&<button className="textbutton" onClick={wakeScreen}>{wakeEnabled?'☀ 已保持亮屏':'☀ 探索时保持亮屏'}</button>}</>}<div className="section-top"><h3>沿途发生</h3><span>{session.events.length} 条</span></div><EventList events={session.events}/></>}
 <div className="save-status"><i/> {sync}</div></>:tab==='history'?<><div className="eyebrow">EVERY STEP COUNTS</div><h1>你的探索足迹。</h1><p className="intro">走过的路，和路上发生的小小惊喜。</p>{!data.history.length?<div className="empty"><span>↝</span><h2>第一段足迹还在路上</h2><p>完成探索后，在这里回看路线和事件。</p><button className="secondary" onClick={()=>setTab('explore')}>去探索</button></div>:data.history.map(s=><button className={'history-card '+(selected?.id===s.id?'on':'')} key={s.id} onClick={()=>{setSelected(s);setFocus(s.quest.boundary[0]);setFocusVersion(v=>v+1);}}><small>{s.demo?'演示探索':'真实探索'} · {new Date(s.startedAt).toLocaleDateString()}</small><strong>{s.quest.name}</strong><span>{label[s.status]} · {s.score} 分 · {Math.round(s.distance)} 米</span></button>)}{selected&&<><div className="action-row"><button className="secondary" onClick={()=>exportSession(selected)}>导出 JSON</button><button className="secondary danger" onClick={async()=>{if(!confirm('删除这次历史记录？'))return;try{setData({...data,history:data.history.filter(s=>s.id!==selected.id)});setSelected(undefined);}catch(e){toast((e as Error).message);}}}>删除记录</button></div><EventList events={selected.events}/></>}</>:<><div className="eyebrow">A LITTLE GUIDE</div><h1>让好奇心带路。</h1><div className="guide"><h2>01 画出你的世界</h2><p>依次点击地图添加至少三个顶点，点击“完成圈区”后，再把宝藏、陷阱和补给放进区域。推荐点位半径 30–50 米。</p><h2>02 带着手机出发</h2><p>在 HTTPS 页面允许精确定位，走进区域开始探索。到点位附近停留至少三秒，等待连续定位确认。</p><h2>03 把惊喜带回来</h2><p>宝藏 +100 分、陷阱 −20 体力、补给 +25 体力。找到全部宝藏即完成。</p><h2>随时暂停，安心回来</h2><p>网页版切后台或锁屏后暂停，不会补记缺失足迹。GPS 信号差时暂停事件判定。请只进入安全、允许通行的地方。</p><h2>记录属于你</h2><p>关卡和足迹只保存在当前浏览器，不上传服务器。清除网站数据或使用无痕模式可能丢失记录，请及时导出备份。导出的 JSON 包含位置与关卡信息。此版本不是竞技反作弊系统。</p><h2>地图与网络</h2><p>底图来自 OpenStreetMap，需要联网。地图加载失败时，已载入的关卡和游戏规则仍可查看。缓存不包含离线地图下载。</p></div></>}
 </aside><section className="map-shell"><MapView boundary={editingBoundary?draftBoundary:q.boundary} drawingBoundary={editingBoundary} points={editingBoundary?[]:visiblePoints} trail={viewing?.trail||[]} position={tab==='explore'?fix?.position:undefined} onTap={tab==='explore'&&(!session||session.demo)?tap:undefined} focus={focus} focusVersion={focusVersion}/><div className="map-top"><span className="map-pill"><i/> {session?.demo?'演示模式':gps}</span><button className="map-pill locate" onClick={()=>{if(session?.demo){if(fix)setFocus(fix.position);}else{pendingFocus.current=true;locate();if(fix&&C.usable(fix)){pendingFocus.current=false;setFocus(fix.position);setFocusVersion(v=>v+1);}}}}>◎ 定位到我</button></div><div className="map-bottom-card"><span>↟</span><div><strong>{viewing?viewing.quest.name:'世界很大，先从身边开始。'}</strong><p>{!secure?'HTTP 体验版：可圈区、布点和演示；浏览器通常不支持在此页面使用真实 GPS。':session?.demo?'点击地图模拟行走，演示不会使用真实 GPS。':session?'保持页面在前台，沿途的发现会自动记录。':editingBoundary?'依次点击地图添加顶点，完成后再布置点位。':'在左侧选择重新圈区或布置点位。拖动地图探索周围。'}</p></div></div><div className="map-legend"><span><i className="treasure"/>宝藏</span><span><i className="trap"/>陷阱</span><span><i className="supply"/>补给</span></div></section></main>
 {notice&&<div className="toast" role="status">{notice}<button aria-label="关闭提示" onClick={()=>setNotice('')}>×</button></div>}
 </div>;
}
function EventList({events}:{events:C.Event[]}){return <ol className="events">{events.slice().reverse().slice(0,100).map(e=><li key={e.id}><i/><div>{e.text}<small>{new Date(e.time).toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit',second:'2-digit'})}</small></div></li>)}</ol>;}
createRoot(document.getElementById('root')!).render(<App/>);
if('serviceWorker'in navigator&&window.isSecureContext)window.addEventListener('load',()=>{navigator.serviceWorker.register(base+'sw.js',{scope:base}).catch(()=>{});});
